Using Numpy, calculate the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix.

The input of the function should be a list containing 9 digits. The function should convert the list into a 3 x 3 Numpy array, and then return a dictionary containing the mean, variance, standard deviation, max, min, and sum along both axes and for the flattened matrix.

In [ ]:
import numpy as np

In [ ]:
given = [0,1,2,3,4,5,6,7,8]
data = np.array(given).reshape(3,3)
print(data)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
f_mean = np.mean(data)
f_var = np.var(data)
f_std = np.std(data)
f_max = np.max(data)
f_min = np.min(data)
f_sum = np.sum(data)
print(f_mean, f_std, f_var, f_max, f_min, f_sum)

4.0 2.581988897471611 6.666666666666667 8 0 36


In [ ]:
ax0_mean = np.mean(data, axis = 0)
ax0_var = np.var(data, axis = 0)
ax0_std = np.std(data, axis = 0)
ax0_max = np.max(data, axis = 0)
ax0_min = np.min(data, axis = 0)
ax0_sum = np.sum(data, axis = 0)
print(ax0_mean, ax0_std, ax0_var, ax0_max, ax0_min, ax0_sum)

[3. 4. 5.] [2.44948974 2.44948974 2.44948974] [6. 6. 6.] [6 7 8] [0 1 2] [ 9 12 15]


In [ ]:
ax1_mean = np.mean(data, axis = 1)
ax1_var = np.var(data, axis = 1)
ax1_std = np.std(data, axis = 1)
ax1_max = np.max(data, axis = 1)
ax1_min = np.min(data, axis = 1)
ax1_sum = np.sum(data, axis = 1)
print(ax1_mean, ax1_std, ax1_var, ax1_max, ax1_min, ax1_sum)

[1. 4. 7.] [0.81649658 0.81649658 0.81649658] [0.66666667 0.66666667 0.66666667] [2 5 8] [0 3 6] [ 3 12 21]


In [ ]:
calculations =  {
    'mean' : [ax0_mean, ax1_mean, f_mean],
    'variance':[ax0_var, ax1_var, f_var],
    'standard deviation':[ax0_std, ax1_std, f_std],
    'max':[ax0_max, ax1_max, f_max],
    'min': [ax0_min, ax1_min, f_min],
    'sum': [ax0_sum, ax1_sum, f_sum]
}
print(calculations)

{'mean': [array([3., 4., 5.]), array([1., 4., 7.]), 4.0], 'variance': [array([6., 6., 6.]), array([0.66666667, 0.66666667, 0.66666667]), 6.666666666666667], 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]), array([0.81649658, 0.81649658, 0.81649658]), 2.581988897471611], 'max': [array([6, 7, 8]), array([2, 5, 8]), 8], 'min': [array([0, 1, 2]), array([0, 3, 6]), 0], 'sum': [array([ 9, 12, 15]), array([ 3, 12, 21]), 36]}
